version: '3.8'

services:
  ce-mongo:
    image: mongo:8.0
    container_name: ce-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  ce-elasticsearch:
    image: elasticsearch:8.13.0
    container_name: ce-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  ce-localstack:
    image: localstack/localstack:latest
    container_name: ce-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,ses,sqs

volumes:
  mongo-data:
